title: Creative Applications of Machine Learning Spring 2019
email: seth@channel.studio
description: >- # this means to ignore newlines until "baseurl:"
  This course will introduce students to the subject of machine learning and its applications in the field of design, particularly for creating interactive applications on the web. Students will gain a top-level understanding of the history and current state of machine learning, as well as an understanding of the frontiers of data organization and style transfer for image, video, and audio.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://courses.channel.studio/spring2019_caml" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

include: 
  - _pages
  - _guides

sass:
  style: compressed
